version: '3.8'

services:
  web:
    build:
      context: ./JunqueiraCrew-Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  parserpdf:
    build:
      context: ./JunqueiraCrew-ParserPDF
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  analisefii:
    build:
      context: ./junqueiracrew-analisefii
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - "GEMINI_API_KEY=AIzaSyAdKEElvOK8UHW3tglgSgrwBQjN47TQuUM"
      - "MODEL=gemini/gemini-2.0-flash-001"
      - GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json