risk_analysis_task:
  description: >
    Analise o texto do relatório presente em {relatorio} e identifique os principais riscos do fundo imobiliário.
    Considere riscos como vacância, inadimplência, concentração de portfólio, localização, etc.
  expected_output: >
    Analise os riscos do fundo de investimento do {relatorio} e forneça uma visão embasada sobre os riscos associados.
    Um JSON como o de exemplo:
    {
    "nome_fundo": "Fundo Imobiliário XPTO",
    "risco_geral": "O fundo possui uma estratégia de longo prazo, com investimentos em imóveis comerciais diversificados...",
    "risco_vacancia": "O risco de vacância é moderado, com contratos de longo prazo e alta taxa de ocupação...",
    "risco_inadimplencia": "A inadimplência tem se mantido baixa, com a maioria dos inquilinos com boa classificação de crédito...",
    "risco_concentracao": "O fundo tem uma boa diversificação geográfica e setorial, mas há concentração em um único setor...",
    "risco_reavaliacao": "O valor dos imóveis tem sido reavaliado anualmente, com boa performance de mercado...",
    "risco_gestao": "A gestão do fundo é altamente experiente e com boa reputação no mercado...",
    }
    Utilize números do texto em {relatorio} para embasar a análise.
    Retorne o JSON, sem formatação adicional. Não utilize blocos de código.
  agent: risk_specialist

dre_analysis_task:
  description: >
    Leia o texto do relatório presente em {relatorio} e extraia os principais dados do Demonstrativo de Resultados (DRE) ou da Distribuição de Resultados.
    Construa um resumo dos indicadores financeiros: receitas, despesas, lucro líquido, FFO, ou qualquer outro indicador financeiro encontrado.
  expected_output: >
    Seção detalhada com os dados do DRE e interpretação dos resultados do fundo.
    Formato em markdown, sem usar blocos de código.
  agent: dre_specialist

csv_structuring_task:
  description: >
    A partir da análise de risco e da análise do DRE, gere uma estrutura de dados tabular (CSV).
    Inclua colunas com os indicadores financeiros e campos categorizados de risco.
  expected_output: >
    CSV em texto puro com cabeçalho e linhas com os dados extraídos. Separador: vírgula.
  agent: csv_builder
